#include<stdio.h>

int main()
{
    int n,i=0,j=0;
    char ch[100];
    scanf("%d",&n);
    if(n>=900)
    {
        ch[j++]='C';
        ch[j++]='M';
        n%=900;
    }
    if(n/500!=0)
    {
        for(i=0;i<(n/500);i++)
            ch[j++]='D';
        n%=500;
    }
    if(n/400!=0)
    {
        ch[j++]='C';
        ch[j++]='D';
        n%=400;
    }
    if(n/100!=0)
    {
        for(i=0;i<(n/100);i++)
            ch[j++]='C';
        n%=100;
    }

    if(n/90!=0)
    {
        ch[j++]='X';
        ch[j++]='C';
        n%=90;
    }
    if(n/50!=0)
    {
        ch[j++]='L';
        n%=50;
    }
    if(n/40!=0)
    {
        ch[j++]='X';
        ch[j++]='L';
        n%=40;
    }
    if(n/10!=0)
    {
        for(i=0;i<(n/10);i++)
            ch[j++]='X';
        n%=10;
    }
    if(n<10)
    {
        if(n==9)
        {
            ch[j++]='I';
            ch[j++]='X';
        }
        if(n==8)
        {
            ch[j++]='V';
            ch[j++]='I';
            ch[j++]='I';
            ch[j++]='I';
        }
        if(n==7)
        {
            ch[j++]='V';
            ch[j++]='I';
            ch[j++]='I';
        }if(n==6)
        {
            ch[j++]='V';
            ch[j++]='I';
        }if(n==5)
        {
            ch[j++]='V';
        }
        if(n==4)
        {
            ch[j++]='I';
            ch[j++]='V';
        }
        if(n==3)
        {
            ch[j++]='I';
            ch[j++]='I';
            ch[j++]='I';
        }
        if(n==2)
        {
            ch[j++]='I';
            ch[j++]='I';
        }
        if(n==1)
        {
            ch[j++]='I';
        }
    }
    ch[j]='\0';
    printf("%s\n",ch);
    return 0;
}
